# Generated by Django 3.2.5 on 2021-09-27 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordremission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messagechat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('sender_id', models.IntegerField()),
                ('reciever_id', models.IntegerField()),
                ('ordremission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmanag.ordremission')),
            ],
        ),
    ]
