# Generated by Django 3.2.5 on 2021-09-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0003_auto_20210928_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ordremission',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiateur', to=settings.AUTH_USER_MODEL)),
                ('ordremission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmanag.ordremission')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='envoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docmanag.envoi'),
            preserve_default=False,
        ),
    ]
