# Generated by Django 3.2.5 on 2021-09-30 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0004_auto_20210928_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envoi',
            options={'ordering': ('createdatenv',)},
        ),
        migrations.AlterModelOptions(
            name='ordremission',
            options={'ordering': ('createdat',)},
        ),
        migrations.RemoveField(
            model_name='ordremission',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='ordremission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordremission',
            name='phone',
        ),
        migrations.AddField(
            model_name='envoi',
            name='createdatenv',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envoi',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envoi',
            name='is_signe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='adresseemploye',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='adressehebergement',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='adressemission',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='datedepart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='dateretour',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='fichier_an_one',
            field=models.FileField(blank=True, null=True, upload_to='userfile/pdfs/'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='fichier_an_two',
            field=models.FileField(blank=True, null=True, upload_to='userfile/pdfs/'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='objetmission',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='signatureemployeur',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='transport',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photoprofil',
            field=models.ImageField(blank=True, null=True, upload_to='userfile/covers/'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='userfile/covers/'),
        ),
    ]
