# Generated by Django 3.2.5 on 2021-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0005_auto_20210930_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi',
            name='is_signe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='adresseemploye',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='adressehebergement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='adressemission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='datedepart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='dateretour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='objetmission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='signatureemployeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='transport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
