# Generated by Django 3.2.5 on 2021-10-06 10:57

from django.db import migrations, models
import docmanag.validate
import docmanag.validator


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0007_ordremission_is_evoiyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordremission',
            name='fichier_genere',
            field=models.FileField(blank=True, null=True, upload_to='userfile/pdfs/', validators=[docmanag.validator.validator]),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='fichier_an_one',
            field=models.FileField(blank=True, null=True, upload_to='userfile/pdfs/', validators=[docmanag.validator.validator]),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='fichier_an_two',
            field=models.FileField(blank=True, null=True, upload_to='userfile/pdfs/', validators=[docmanag.validator.validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photoprofil',
            field=models.ImageField(blank=True, null=True, upload_to='userfile/covers/', validators=[docmanag.validate.validator_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='userfile/covers/', validators=[docmanag.validate.validator_image]),
        ),
    ]
