# Generated by Django 3.2.5 on 2021-10-06 11:28

from django.db import migrations, models
import docmanag.models
import docmanag.validator


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0008_auto_20211006_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordremission',
            name='fichier_an_one',
            field=models.FileField(blank=True, null=True, upload_to=docmanag.models.pdffile, validators=[docmanag.validator.validator]),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='fichier_an_two',
            field=models.FileField(blank=True, null=True, upload_to=docmanag.models.pdffile, validators=[docmanag.validator.validator]),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='fichier_genere',
            field=models.FileField(blank=True, null=True, upload_to=docmanag.models.pdffile, validators=[docmanag.validator.validator]),
        ),
    ]
