# Generated by Django 3.2.5 on 2021-10-17 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0009_auto_20211006_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordremission',
            name='datecreat',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordremission',
            name='motif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
