# Generated by Django 3.2.5 on 2021-10-18 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0012_ordremission_is_signer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordremission',
            name='datecreat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
