# Generated by Django 3.2.5 on 2021-10-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanag', '0013_alter_ordremission_datecreat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordremission',
            name='kilomarrivee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='kilomdepart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='nomchauffeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
